### ISSUE TITLE
pip install not working

### ISSUE THREAD

**Issue by wcollins-ebsco** [krishnanlab/PecanPy#79]
>pip install pecanpy
ERROR: Could not find a version that satisfies the requirement pecanpy (from versions: none)
ERROR: No matching distribution found for pecanpy

I've attempted installing on Linux and Windows.

**Comment by RemyLau** [comment]
Thanks for reporting the issue @wcollins-ebsco! This might be due to conflicted dependencies with other libraries you have installed. If you don't mind, could you try to install PecanPy in a clean environment? You could create virtual environments using, for example, [conda](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html) or [Virtualenv](https://virtualenv.pypa.io/en/latest/index.html).

**Comment by RemyLau** [comment]
Hi @wcollins-ebsco, just checking to see if you have figured out a solution for this? I know dealing with dependencies from different libraries could be very frustrating. I'm very happy to help you sort this out by setting up the environment if you are still encountering the issue with dependency versions, as you posted above.

**Comment by riyaj8888** [comment]
i tried in clean environment but unable to import 

ImportError: cannot import name 'node2vec' from 'pecanpy'

**Comment by RemyLau** [comment]
Hi @riyaj8888, thanks for the comment. As of [v2.0.2](https://github.com/krishnanlab/PecanPy/releases/tag/v2.0.2), `node2vec` is renamed to `pecanpy`. Try to do `import pecanpy from pecanpy` instead and let me know if this resolves the issue.

**Comment by RemyLau** [comment]
I will close this issue for now as there are not many updates. Feel free to reopen if you are still encountering this problem with more details, and I will try my best to help you troubleshoot.
