### ISSUE TITLE
get_normalized_probs missing

### ISSUE THREAD

**Issue by ThanosSkentzos** [krishnanlab/PecanPy#80]
Hello, thanks for sharing this great project!

I am having an issue while trying to run the **.simulate_walks** function through python. I get this message

AttributeError: 'DenseOTF' object has no attribute 'get_normalized_probs'

It seems that the Base Class is missing the **get_normalized_probs** function.
Does anyone have this bug?

----------------------------
win 10
python 3.8.5
pip 22.0.3
pecanpy 2.0.2

**Comment by RemyLau** [comment]
Hi @ThanosSkentzos, thanks for your interest in PecanPy and the issue! In the current version (v2.0.2), you need to call [``setup_get_noramlized_probs``](https://github.com/krishnanlab/PecanPy/blob/76bd6a1dd31afcccca498c66189073001219976e/src/pecanpy/pecanpy.py#L185-L202) first in order to use ``get_normalized_probs``. This is needed to distinguish between node2vec and a variant of node2vec called node2vec+.

I also agree that this dependency of a class attribute is a bit confusing and indeed, I'm planning on a major refactoring to resolve this issue in the near future. But for now, you need to call ``setup_get_normalized_probs`` before using ``get_normalized_probs``.

**Comment by ThanosSkentzos** [comment]
Hi @RemyLau, I didn't call `get_normalized_probs`.
I actually run `simulate_walks` which correctly called `setup_get_normalized_probs` as you mentioned.
The actual problem is that I was importing the models by using `from pecanpy import node2vec` instead of `from pecanpy import pecanpy` which was missing the `get_normalized_probs` function.
Thanks
